export const ADD_TEST_REQUEST = "ADD_TEST_REQUEST";
export const ADD_TEST_SUCCESS = "ADD_TEST_SUCCESS";
export const ADD_TEST_FAIL = "ADD_TEST_FAIL";

export const DELETE_TEST_REQUEST = "DELETE_TEST_REQUEST";
export const DELETE_TEST_SUCCESS = "DELETE_TEST_SUCCESS";
export const DELETE_TEST_FAIL = "DELETE_TEST_FAIL";

export const UPDATE_TEST_REQUEST = "UPDATE_TEST_REQUEST";
export const UPDATE_TEST_SUCCESS = "UPDATE_TEST_SUCCESS";
export const UPDATE_TEST_FAIL = "UPDATE_TEST_FAIL";

export const GET_ADMIN_TESTS_REQUEST = "GET_ADMIN_TESTS_REQUEST";
export const GET_ADMIN_TESTS_SUCCESS = "GET_ADMIN_TESTS_SUCCESS";
export const GET_ADMIN_TESTS_FAIL = "GET_ADMIN_TESTS_FAIL";
export const GET_CLIENT_TESTS_REQUEST = "GET_CLIENT_TESTS_REQUEST";
export const GET_CLIENT_TESTS_SUCCESS = "GET_CLIENT_TESTS_SUCCESS";
export const GET_CLIENT_TESTS_FAIL = "GET_CLIENT_TESTS_FAIL";

export const GET_ADIM_TEST_REQUEST = "GET_ADIM_TEST_REQUEST";
export const GET_ADIM_TEST_SUCCESS = "GET_ADIM_TEST_SUCCESS";
export const GET_ADIM_TEST_FAIL = "GET_ADIM_TEST_FAIL";

export const GET_CLIENT_TEST_REQUEST = "GET_CLIENT_TEST_REQUEST";
export const GET_CLIENT_TEST_SUCCESS = "GET_CLIENT_TEST_SUCCESS";
export const GET_CLIENT_TEST_FAIL = "GET_CLIENT_TEST_FAIL";
